//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.KHACHes = new HashSet<KHACH>();
            this.NhanViens = new HashSet<NhanVien>();
        }

        [DisplayName("Nhập Tên đăng nhập")]
        [Required(ErrorMessage = "Not a valid phone number")]  
        [RegularExpression(@"[0-9]{10}", ErrorMessage = "Not a valid phone number")]
        public string IdA { get; set; }

        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Không để trống")]
        [DataType(DataType.Password)]
        public string PassA { get; set; }
        public int MaQuyen { get; set; }

        [DisplayName("Nhập Họ tên người dùng")]
        [Required(ErrorMessage = "Không để trống")]
        public string TenUser { get; set; }

        [NotMapped]
        [Compare("PassA")]
        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không trùng")]
        public string ConfirmPassA { get; set; }

        public string Error { get; set; }
        public string ErrorDangKy { get; set; }

        public virtual PhanQuyen PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACH> KHACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
