//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int SoHD { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public int MaKhach { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string HTTT { get; set; }
        public string DieuKhoan { get; set; }
        public double TraTruoc { get; set; }
    
        public virtual ChiTietHopDong ChiTietHopDong { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
